# This is a basic workflow to help you get started with Actions

name: Manual release action

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Is this pre-release?'
        required: true
        type: boolean
      version:
        description: 'Is this pre-release?'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: ZIPs the contents
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: Post-Setup.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Post-Setup
          path: Post-Setup.zip
      - name: Create Relese
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "Post*"
          tag: "v${{ env.VER }}"
          name: "PostSetup-${{ inputs.version }}"
          prerelease: "${{ inputs.nightly }}"
          bodyFile: "README.md"
